using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 using System.Globalization;
        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;
namespace discordbot.Modules.Warframe
{
    public partial class Solnodes
    {
        public string SolNode0 { get; set; }
        public string SolNode1 { get; set; }
        public string SolNode2 { get; set; }
        public string SolNode3 { get; set; }
        public string SolNode4 { get; set; }
        public string SolNode5 { get; set; }
        public string SolNode6 { get; set; }
        public string SolNode7 { get; set; }
        public string SolNode8 { get; set; }
        public string SolNode9 { get; set; }
        public string SolNode10 { get; set; }
        public string SolNode11 { get; set; }
        public string SolNode12 { get; set; }
        public string SolNode13 { get; set; }
        public string SolNode14 { get; set; }
        public string SolNode15 { get; set; }
        public string SolNode16 { get; set; }
        public string SolNode17 { get; set; }
        public string SolNode18 { get; set; }
        public string SolNode19 { get; set; }
        public string SolNode20 { get; set; }
        public string SolNode21 { get; set; }
        public string SolNode22 { get; set; }
        public string SolNode23 { get; set; }
        public string SolNode24 { get; set; }
        public string SolNode25 { get; set; }
        public string SolNode26 { get; set; }
        public string SolNode27 { get; set; }
        public string SolNode28 { get; set; }
        public string SolNode29 { get; set; }
        public string SolNode30 { get; set; }
        public string SolNode31 { get; set; }
        public string SolNode32 { get; set; }
        public string SolNode33 { get; set; }
        public string SolNode34 { get; set; }
        public string SolNode35 { get; set; }
        public string SolNode36 { get; set; }
        public string SolNode37 { get; set; }
        public string SolNode38 { get; set; }
        public string SolNode39 { get; set; }
        public string SolNode40 { get; set; }
        public string SolNode41 { get; set; }
        public string SolNode42 { get; set; }
        public string SolNode43 { get; set; }
        public string SolNode44 { get; set; }
        public string SolNode45 { get; set; }
        public string SolNode46 { get; set; }
        public string SolNode47 { get; set; }
        public string SolNode48 { get; set; }
        public string SolNode49 { get; set; }
        public string SolNode50 { get; set; }
        public string SolNode51 { get; set; }
        public string SolNode52 { get; set; }
        public string SolNode53 { get; set; }
        public string SolNode54 { get; set; }
        public string SolNode55 { get; set; }
        public string SolNode56 { get; set; }
        public string SolNode57 { get; set; }
        public string SolNode58 { get; set; }
        public string SolNode59 { get; set; }
        public string SolNode60 { get; set; }
        public string SolNode61 { get; set; }
        public string SolNode62 { get; set; }
        public string SolNode63 { get; set; }
        public string SolNode64 { get; set; }
        public string SolNode65 { get; set; }
        public string SolNode66 { get; set; }
        public string SolNode67 { get; set; }
        public string SolNode68 { get; set; }
        public string SolNode69 { get; set; }
        public string SolNode70 { get; set; }
        public string SolNode71 { get; set; }
        public string SolNode72 { get; set; }
        public string SolNode73 { get; set; }
        public string SolNode74 { get; set; }
        public string SolNode75 { get; set; }
        public string SolNode76 { get; set; }
        public string SolNode77 { get; set; }
        public string SolNode78 { get; set; }
        public string SolNode79 { get; set; }
        public string SolNode80 { get; set; }
        public string SolNode81 { get; set; }
        public string SolNode82 { get; set; }
        public string SolNode83 { get; set; }
        public string SolNode84 { get; set; }
        public string SolNode85 { get; set; }
        public string SolNode86 { get; set; }
        public string SolNode87 { get; set; }
        public string SolNode88 { get; set; }
        public string SolNode89 { get; set; }
        public string SolNode90 { get; set; }
        public string SolNode91 { get; set; }
        public string SolNode92 { get; set; }
        public string SolNode93 { get; set; }
        public string SolNode94 { get; set; }
        public string SolNode95 { get; set; }
        public string SolNode96 { get; set; }
        public string SolNode97 { get; set; }
        public string SolNode98 { get; set; }
        public string SolNode99 { get; set; }
        public string SolNode100 { get; set; }
        public string SolNode101 { get; set; }
        public string SolNode102 { get; set; }
        public string SolNode103 { get; set; }
        public string SolNode104 { get; set; }
        public string SolNode105 { get; set; }
        public string SolNode106 { get; set; }
        public string SolNode107 { get; set; }
        public string SolNode108 { get; set; }
        public string SolNode109 { get; set; }
        public string SolNode110 { get; set; }
        public string SolNode111 { get; set; }
        public string SolNode112 { get; set; }
        public string SolNode113 { get; set; }
        public string SolNode114 { get; set; }
        public string SolNode115 { get; set; }
        public string SolNode116 { get; set; }
        public string SolNode117 { get; set; }
        public string SolNode118 { get; set; }
        public string SolNode119 { get; set; }
        public string SolNode120 { get; set; }
        public string SolNode121 { get; set; }
        public string SolNode122 { get; set; }
        public string SolNode123 { get; set; }
        public string SolNode124 { get; set; }
        public string SolNode125 { get; set; }
        public string SolNode126 { get; set; }
        public string SolNode127 { get; set; }
        public string SolNode128 { get; set; }
        public string SolNode129 { get; set; }
        public string SolNode130 { get; set; }
        public string SolNode131 { get; set; }
        public string SolNode132 { get; set; }
        public string SolNode133 { get; set; }
        public string SolNode134 { get; set; }
        public string SolNode135 { get; set; }
        public string SolNode136 { get; set; }
        public string SolNode137 { get; set; }
        public string SolNode138 { get; set; }
        public string SolNode139 { get; set; }
        public string SolNode140 { get; set; }
        public string SolNode141 { get; set; }
        public string SolNode142 { get; set; }
        public string SolNode143 { get; set; }
        public string SolNode144 { get; set; }
        public string SolNode145 { get; set; }
        public string SolNode146 { get; set; }
        public string SolNode147 { get; set; }
        public string SolNode148 { get; set; }
        public string SolNode149 { get; set; }
        public string SolNode150 { get; set; }
        public string SolNode151 { get; set; }
        public string SolNode152 { get; set; }
        public string SolNode153 { get; set; }
        public string SolNode154 { get; set; }
        public string SolNode155 { get; set; }
        public string SolNode156 { get; set; }
        public string SolNode157 { get; set; }
        public string SolNode158 { get; set; }
        public string SolNode159 { get; set; }
        public string SolNode160 { get; set; }
        public string SolNode161 { get; set; }
        public string SolNode162 { get; set; }
        public string SolNode163 { get; set; }
        public string SolNode164 { get; set; }
        public string SolNode165 { get; set; }
        public string SolNode166 { get; set; }
        public string SolNode167 { get; set; }
        public string SolNode168 { get; set; }
        public string SolNode169 { get; set; }
        public string SolNode170 { get; set; }
        public string SolNode171 { get; set; }
        public string SolNode172 { get; set; }
        public string SolNode173 { get; set; }
        public string SolNode174 { get; set; }
        public string SolNode175 { get; set; }
        public string SolNode176 { get; set; }
        public string SolNode177 { get; set; }
        public string SolNode178 { get; set; }
        public string SolNode179 { get; set; }
        public string SolNode180 { get; set; }
        public string SolNode181 { get; set; }
        public string SolNode182 { get; set; }
        public string SolNode183 { get; set; }
        public string SolNode184 { get; set; }
        public string SolNode185 { get; set; }
        public string SolNode186 { get; set; }
        public string SolNode187 { get; set; }
        public string SolNode188 { get; set; }
        public string SolNode189 { get; set; }
        public string SolNode190 { get; set; }
        public string SolNode191 { get; set; }
        public string SolNode192 { get; set; }
        public string SolNode193 { get; set; }
        public string SolNode194 { get; set; }
        public string SolNode195 { get; set; }
        public string SolNode196 { get; set; }
        public string SolNode197 { get; set; }
        public string SolNode198 { get; set; }
        public string SolNode199 { get; set; }
        public string SolNode200 { get; set; }
        public string SolNode201 { get; set; }
        public string SolNode202 { get; set; }
        public string SolNode203 { get; set; }
        public string SolNode204 { get; set; }
        public string SolNode205 { get; set; }
        public string SolNode206 { get; set; }
        public string SolNode207 { get; set; }
        public string SolNode208 { get; set; }
        public string SolNode209 { get; set; }
        public string SolNode210 { get; set; }
        public string SolNode211 { get; set; }
        public string SolNode212 { get; set; }
        public string SolNode213 { get; set; }
        public string SolNode214 { get; set; }
        public string SolNode215 { get; set; }
        public string SolNode216 { get; set; }
        public string SolNode217 { get; set; }
        public string SolNode218 { get; set; }
        public string SolNode219 { get; set; }
        public string SolNode220 { get; set; }
        public string SolNode221 { get; set; }
        public string SolNode222 { get; set; }
        public string SolNode223 { get; set; }
        public string SolNode224 { get; set; }
        public string SolNode225 { get; set; }
        public string SolNode226 { get; set; }
        public string SolNode227 { get; set; }
        public string SolNode228 { get; set; }
        public string SolNode400 { get; set; }
        public string SolNode401 { get; set; }
        public string SolNode402 { get; set; }
        public string SolNode403 { get; set; }
        public string SolNode404 { get; set; }
        public string SolNode405 { get; set; }
        public string SolNode406 { get; set; }
        public string SolNode407 { get; set; }
        public string SolNode408 { get; set; }
        public string SolNode409 { get; set; }
        public string SolNode410 { get; set; }
        public string SolNode411 { get; set; }
        public string SolNode412 { get; set; }
        public string SolNode413 { get; set; }
        public string SolNode741 { get; set; }
        public string SolNode742 { get; set; }
        public string SolNode743 { get; set; }
        public string SolNode744 { get; set; }
        public string SolNode745 { get; set; }
        public string SolNode746 { get; set; }
        public string SolNode747 { get; set; }
        public string SolNode748 { get; set; }
        public string SolNode901 { get; set; }
        public string SolNode902 { get; set; }
        public string SolNode903 { get; set; }
        public string SolNode904 { get; set; }
        public string SolNode905 { get; set; }
        public string SolNode906 { get; set; }
        public string SolNode907 { get; set; }
        public string SolNode908 { get; set; }
        public string SolNode300 { get; set; }
        public string SolNode301 { get; set; }
        public string SolNode302 { get; set; }
        public string SolNode304 { get; set; }
        public string SolNode305 { get; set; }
        public string SolNode306 { get; set; }
        public string SolNode307 { get; set; }
        public string SettlementNode1 { get; set; }
        public string SettlementNode2 { get; set; }
        public string SettlementNode3 { get; set; }
        public string SettlementNode4 { get; set; }
        public string SettlementNode5 { get; set; }
        public string SettlementNode6 { get; set; }
        public string SettlementNode7 { get; set; }
        public string SettlementNode8 { get; set; }
        public string SettlementNode9 { get; set; }
        public string SettlementNode10 { get; set; }
        public string SettlementNode11 { get; set; }
        public string SettlementNode12 { get; set; }
        public string SettlementNode13 { get; set; }
        public string SettlementNode14 { get; set; }
        public string SettlementNode15 { get; set; }
        public string SettlementNode16 { get; set; }
        public string SettlementNode17 { get; set; }
        public string SettlementNode18 { get; set; }
        public string SettlementNode19 { get; set; }
        public string SettlementNode20 { get; set; }
        public string MercuryHub { get; set; }
        public string VenusHub { get; set; }
        public string EarthHub { get; set; }
        public string SaturnHub { get; set; }
        public string ErisHub { get; set; }
        public string EuropaHub { get; set; }
        public string PlutoHub { get; set; }
        public string EventNode0 { get; set; }
        public string EventNode1 { get; set; }
        public string EventNode2 { get; set; }
        public string EventNode3 { get; set; }
        public string EventNode4 { get; set; }
        public string EventNode5 { get; set; }
        public string EventNode6 { get; set; }
        public string EventNode7 { get; set; }
        public string EventNode8 { get; set; }
        public string EventNode9 { get; set; }
        public string EventNode10 { get; set; }
        public string EventNode11 { get; set; }
        public string EventNode12 { get; set; }
        public string EventNode13 { get; set; }
        public string EventNode14 { get; set; }
        public string EventNode15 { get; set; }
        public string EventNode16 { get; set; }
        public string EventNode17 { get; set; }
        public string EventNode18 { get; set; }
        public string EventNode19 { get; set; }
        public string EventNode20 { get; set; }
        public string EventNode22 { get; set; }
        public string EventNode761 { get; set; }
        public string EventNode762 { get; set; }
        public string EventNode763 { get; set; }
        public string PvpNode0 { get; set; }
        public string PvpNode1 { get; set; }
        public string PvpNode2 { get; set; }
        public string PvpNode3 { get; set; }
        public string PvpNode4 { get; set; }
        public string PvpNode5 { get; set; }
        public string PvpNode6 { get; set; }
        public string PvpNode7 { get; set; }
        public string PvpNode8 { get; set; }
        public string PvpNode9 { get; set; }
        public string PvpNode10 { get; set; }
        public string PvpNode11 { get; set; }
        public string PvpNode12 { get; set; }
        public string PvpNode13 { get; set; }
        public string PvpNode14 { get; set; }
        public string ClanNode0 { get; set; }
        public string ClanNode1 { get; set; }
        public string ClanNode2 { get; set; }
        public string ClanNode3 { get; set; }
        public string ClanNode4 { get; set; }
        public string ClanNode5 { get; set; }
        public string ClanNode6 { get; set; }
        public string ClanNode7 { get; set; }
        public string ClanNode8 { get; set; }
        public string ClanNode9 { get; set; }
        public string ClanNode10 { get; set; }
        public string ClanNode11 { get; set; }
        public string ClanNode12 { get; set; }
        public string ClanNode13 { get; set; }
        public string ClanNode14 { get; set; }
        public string ClanNode15 { get; set; }
        public string ClanNode16 { get; set; }
        public string ClanNode17 { get; set; }
        public string ClanNode18 { get; set; }
        public string ClanNode19 { get; set; }
        public string ClanNode20 { get; set; }
        public string ClanNode21 { get; set; }
        public string ClanNode22 { get; set; }
        public string ClanNode23 { get; set; }
        public string ClanNode24 { get; set; }
        public string ClanNode25 { get; set; }
       
        }
    }
